// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'buttonLink': string;
  'mainText': string;
  'subtext': string;
}
export const cssExports: CssExports;
export default cssExports;
