// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'resource': string;
  'resourceGrid': string;
  'resourceGridFrame': string;
  'resourceText': string;
  'resourceTextColored': string;
}
export const cssExports: CssExports;
export default cssExports;
