// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'item': string;
  'price': string;
  'text': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
