// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'burgerLink': string;
  'caption': string;
  'heading1': string;
  'heading1Accent': string;
  'heading2': string;
  'heading2Accent': string;
  'heading3': string;
  'text': string;
  'textButton': string;
  'textLink': string;
}
export const cssExports: CssExports;
export default cssExports;
