// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'column': string;
  'contactBlock': string;
  'contactHeading': string;
  'contactText': string;
  'footer': string;
  'motto': string;
  'mottoColored': string;
  'social': string;
  'socialLink': string;
}
export const cssExports: CssExports;
export default cssExports;
