// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttonsBlock': string;
  'dowloadBlock': string;
  'textContent': string;
  'textHeading': string;
  'textHeadingColored': string;
}
export const cssExports: CssExports;
export default cssExports;
