// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'slider': string;
  'sliderBlock': string;
  'sliderInner': string;
  'sliderTrack': string;
  'title': string;
  'titleMarked': string;
}
export const cssExports: CssExports;
export default cssExports;
